import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { persons } from '../data/persons'
import {PersonCard} from "../src/components/PersonCard/PersonCard";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Star Wars persons</h3>
        <div className={styles['person-container']}>
          {persons.map(({name, id, img}) => <PersonCard name={name} img={img} key={id} />)}
        </div>
      </main>
    </div>
  )
}

export default Home
