import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {PersonCard} from "../src/components/PersonCard/PersonCard";
import {useEffect, useState} from "react";
import {Person} from "../src/types/Person";

const Home: NextPage = () => {
  const [persons, setPersons] = useState<Person[]>()
  useEffect(function fetchPerson() {
     fetch('/api/persons')
       .then(async (data) => {
         setPersons(await data.json())
       })
       .catch(() => setPersons([]))
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Star Wars persons</h3>
        {!persons?.length
          ? <>Loading...</>
          : <div className={styles['person-container']}>
            {persons.map(({name, id, img}) => <PersonCard name={name} img={img} key={id}/>)}
          </div>
        }
      </main>
    </div>
  )
}

export default Home
